import React from "react";
const columns = [
  {name: "No.", uid: "id"},
  {name: "Name", uid: "fullname"},
  {name: "Room", uid: "room"},
  {name: "Check-in Date", uid: "CheckInDate"},
  {name: "Check-out Date", uid: "CheckOutDate"},
  {name: "STATUS", uid: "status"},
  {name: "ACTIONS", uid: "actions"},
];

const users = [
  {
    id: 1,
    fullname: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "approve",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
    CheckInDate:"1/02/44",
    CheckOutDate:"2/02/44",
    room:"A",
  },
  {
    id: 2,
    fullname: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "waiting",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
    CheckInDate:"1/02/44",
    CheckOutDate:"2/02/44",
    room:"A",
  },
  {
    id: 3,
    fullname: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "waiting",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
    CheckInDate:"1/02/44",
    CheckOutDate:"2/02/44",
    room:"A",
  },
  {
    id: 4,
    fullname: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "waiting",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
    CheckInDate:"1/02/44",
    CheckOutDate:"2/02/44",
    room:"C",
  },
  {
    id: 5,
    fullname: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "waiting",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
    CheckInDate:"1/02/44",
    CheckOutDate:"2/02/44",
    room:"B",
  },
];

export {columns, users};
